#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Hides folders in Obsidian that do not contain any .md files
(directly or within subfolders) by generating a CSS snippet.

Expected Structure:
Bastien-Antigravity/
├── .obsidian/
├── obsidian-brain/
│   └── 05-Scripts/
│       └── Hide-Empty-Folders.py   <-- this script
"""

from os import walk as osWalk
from pathlib import Path as pathlibPath

# ==========================================================
# AUTOMATIC LOCALIZATION
# ==========================================================

SCRIPT_DIR = pathlibPath(__file__).resolve().parent

# Move up from 'obsidian-brain/05-Scripts' to the root 'Bastien-Antigravity'
VAULT_ROOT = SCRIPT_DIR.parents[1]

OBSIDIAN_DIR = VAULT_ROOT / ".obsidian"
SNIPPETS_DIR = OBSIDIAN_DIR / "snippets"
CSS_FILE = SNIPPETS_DIR / "Hide-Empty-Folders.css"

# Directories to ignore completely
IGNORE_DIRS = {
    ".obsidian",
    ".git",
}

# ==========================================================
# TOOLS
# ==========================================================


def contains_md_recursive(folder: pathlibPath) -> bool:
    """
    True if this folder contains at least one .md file
    within itself or any sub-folder.
    """
    for root, dirs, files in osWalk(folder):
        # Ignore technical directories
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]

        for file in files:
            if file.lower().endswith(".md"):
                return True

    return False


def css_escape(path_str: str) -> str:
    """
    Escapes quotes for CSS selectors.
    """
    return path_str.replace("\\", "/").replace('"', '\\"')


# ==========================================================
# SCAN
# ==========================================================

folders_to_hide = []

for root, dirs, files in osWalk(VAULT_ROOT):
    root_path = pathlibPath(root)

    # Ignore technical directories
    dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]

    # Do not process the root itself
    if root_path == VAULT_ROOT:
        continue

    # If the folder contains no .md recursively, hide it
    if not contains_md_recursive(root_path):
        rel_path = root_path.relative_to(VAULT_ROOT).as_posix()
        folders_to_hide.append(rel_path)

# ==========================================================
# CSS GENERATION
# ==========================================================

SNIPPETS_DIR.mkdir(parents=True, exist_ok=True)

lines = [
    "/* File automatically generated by Hide-Empty-Folders.py */",
    "/* Hides folders containing no documentation (.md) in the sidebar */",
    "",
]

for rel_path in sorted(folders_to_hide):
    safe = css_escape(rel_path)
    # Target both the folder title and its children container
    lines.append(f'.nav-folder-title[data-path="{safe}"],')
    lines.append(
        f'.nav-folder-title[data-path="{safe}"] + .nav-folder-children {{ display: none !important; }}'
    )

CSS_FILE.write_text("\n".join(lines), encoding="utf-8")

print(f"CSS generated: {CSS_FILE}")
print(f"Hidden folders: {len(folders_to_hide)}")
print("")
print("In Obsidian:")
print("Settings > Appearance > CSS Snippets > activate Hide-Empty-Folders.css")
