#!/usr/bin/env python
# coding:utf-8
"""
ESSENTIAL PROCESS:
Hides folders in Obsidian that do not contain any .md files 
(directly or recursively) by generating a CSS snippet for the UI.

DATA FLOW:
1. Crawls the vault root to identify empty folders.
2. Checks for .md file presence in each folder recursively.
3. Generates CSS selectors targeting [data-path] attributes.
4. Writes the result to .obsidian/snippets/Hide-Empty-Folders.css.

KEY PARAMETERS:
- VAULT_ROOT: The target Obsidian vault root.
- IGNORE_DIRS: Technical folders to skip during the scan.
"""
import os, sys
# Ensure we are running inside the virtual environment
_venv_dir = os.path.dirname(os.path.abspath(__file__))
while _venv_dir and _venv_dir != '/' and not os.path.exists(os.path.join(_venv_dir, ".venv")):
    _parent = os.path.dirname(_venv_dir)
    if _parent == _venv_dir:
        break
    _venv_dir = _parent
_venv_python = os.path.join(_venv_dir, ".venv", "Scripts", "python.exe") if os.name == "nt" else os.path.join(_venv_dir, ".venv", "bin", "python3")
if os.path.exists(_venv_python):
    try:
        if not os.path.samefile(sys.executable, _venv_python):
            os.execl(_venv_python, _venv_python, *sys.argv)
    except OSError:
        pass


from os import walk as osWalk
from pathlib import Path
from typing import List

# ### CONFIGURATIONS ###

SCRIPT_DIR = Path(__file__).resolve().parent
# tech-stack-brain/05-Project-Scripts -> parent is tech-stack-brain -> parent is obsidian-brain (VAULT_ROOT)
VAULT_ROOT = SCRIPT_DIR.parents[1]

OBSIDIAN_DIR = VAULT_ROOT / ".obsidian"
SNIPPETS_DIR = OBSIDIAN_DIR / "snippets"
CSS_FILE = SNIPPETS_DIR / "Hide-Empty-Folders.css"

# Directories to ignore completely
IGNORE_DIRS = {
    ".obsidian",
    ".git",
}

# -----------------------------------------------------------------------------------------------

def contains_md_recursive(folder: Path) -> bool:
    """
    True if this folder contains at least one .md file 
    within itself or any sub-folder.
    """
    for root, dirs, files in osWalk(folder):
        # Ignore technical directories
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]

        for file in files:
            if file.lower().endswith(".md"):
                return True

    return False

# -----------------------------------------------------------------------------------------------

def css_escape(path_str: str) -> str:
    """
    Escapes quotes and normalizes slashes for CSS selectors.
    """
    return path_str.replace("\\", "/").replace('"', '\\"')

# -----------------------------------------------------------------------------------------------

def main() -> None:
    """
    Scans the vault and generates the CSS snippet.
    """
    if not VAULT_ROOT.exists():
        print("HideEmptyFolders: Vault root not found at {0}".format(VAULT_ROOT))
        return

    folders_to_hide = []

    for root, dirs, files in osWalk(VAULT_ROOT):
        root_path = Path(root)

        # Ignore technical directories
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]

        # Do not process the root itself
        if root_path == VAULT_ROOT:
            continue

        # If the folder contains no .md recursively, hide it
        if not contains_md_recursive(root_path):
            try:
                rel_path = root_path.relative_to(VAULT_ROOT).as_posix()
                folders_to_hide.append(rel_path)
            except ValueError:
                continue

    # Generate CSS
    SNIPPETS_DIR.mkdir(parents=True, exist_ok=True)

    lines = [
        "/* File automatically generated by Hide-Empty-Folders.py */",
        "/* Hides folders containing no documentation (.md) in the sidebar */",
        "",
    ]

    for rel_path in sorted(folders_to_hide):
        safe = css_escape(rel_path)
        # Target both the folder title and its children container
        lines.append('.nav-folder-title[data-path="{0}"],'.format(safe))
        lines.append(
            '.nav-folder-title[data-path="{0}"] + .nav-folder-children {{ display: none !important; }}'.format(safe)
        )

    CSS_FILE.write_text("\n".join(lines), encoding="utf-8")

    print("CSS generated: {0}".format(CSS_FILE))
    print("Hidden folders: {0}".format(len(folders_to_hide)))
    print("\nIn Obsidian:")
    print("Settings > Appearance > CSS Snippets > activate Hide-Empty-Folders.css")

# -----------------------------------------------------------------------------------------------

if __name__ == "__main__":
    main()
